// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiCompare.Data;

#nullable disable

namespace OptiCompare.Migrations
{
    [DbContext(typeof(OptiCompareDbContext))]
    [Migration("20240323223826_rnullables")]
    partial class rnullables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OptiCompare.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpu")
                        .HasColumnType("longtext");

                    b.Property<string>("Gpu")
                        .HasColumnType("longtext");

                    b.Property<string>("Os")
                        .HasColumnType("longtext");

                    b.Property<string>("RAM")
                        .HasColumnType("longtext");

                    b.Property<string>("batteryCapacity")
                        .HasColumnType("longtext");

                    b.Property<string>("batteryLifeTest")
                        .HasColumnType("longtext");

                    b.Property<string>("bodyHeight")
                        .HasColumnType("longtext");

                    b.Property<string>("bodyThickness")
                        .HasColumnType("longtext");

                    b.Property<string>("bodyWeight")
                        .HasColumnType("longtext");

                    b.Property<string>("bodyWidth")
                        .HasColumnType("longtext");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("chargingSpeed")
                        .HasColumnType("longtext");

                    b.Property<string>("displayResolution")
                        .HasColumnType("longtext");

                    b.Property<string>("displaySize")
                        .HasColumnType("longtext");

                    b.Property<string>("displayType")
                        .HasColumnType("longtext");

                    b.Property<string>("frontCameraDetails")
                        .HasColumnType("longtext");

                    b.Property<bool>("hasNetwork5GBands")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("image")
                        .HasColumnType("longtext");

                    b.Property<string>("mainCameraDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("modelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("price")
                        .HasColumnType("longtext");

                    b.Property<string>("storage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Phone");
                });
#pragma warning restore 612, 618
        }
    }
}
