// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiCompare.Data;

#nullable disable

namespace OptiCompare.Migrations
{
    [DbContext(typeof(OptiCompareDbContext))]
    [Migration("20240324190629_phoneUpdate")]
    partial class phoneUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OptiCompare.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("hasNetwork5GBands")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("image")
                        .HasColumnType("longtext");

                    b.Property<string>("modelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("price")
                        .HasColumnType("longtext");

                    b.Property<string>("storage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("OptiCompare.Models.Phone", b =>
                {
                    b.OwnsOne("OptiCompare.Models.BatteryDetails", "BatteryDetails", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("int");

                            b1.Property<string>("batteryCapacity")
                                .HasColumnType("longtext");

                            b1.Property<string>("batteryLifeTest")
                                .HasColumnType("longtext");

                            b1.Property<string>("chargingSpeed")
                                .HasColumnType("longtext");

                            b1.HasKey("PhoneId");

                            b1.ToTable("Phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId");
                        });

                    b.OwnsOne("OptiCompare.Models.BodyDimensions", "BodyDimensions", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("int");

                            b1.Property<string>("bodyHeight")
                                .HasColumnType("longtext");

                            b1.Property<string>("bodyThickness")
                                .HasColumnType("longtext");

                            b1.Property<string>("bodyWeight")
                                .HasColumnType("longtext");

                            b1.Property<string>("bodyWidth")
                                .HasColumnType("longtext");

                            b1.HasKey("PhoneId");

                            b1.ToTable("Phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId");
                        });

                    b.OwnsOne("OptiCompare.Models.CameraDetails", "CameraDetails", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("int");

                            b1.Property<string>("frontCameraDetails")
                                .HasColumnType("longtext");

                            b1.Property<string>("mainCameraDetails")
                                .HasColumnType("longtext");

                            b1.HasKey("PhoneId");

                            b1.ToTable("Phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId");
                        });

                    b.OwnsOne("OptiCompare.Models.DisplayDetails", "DisplayDetails", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("int");

                            b1.Property<string>("displayProtection")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("displayResolution")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("displaySize")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("displayType")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("PhoneId");

                            b1.ToTable("Phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId");
                        });

                    b.OwnsOne("OptiCompare.Models.PlatformDetails", "PlatformDetails", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("int");

                            b1.Property<string>("Cpu")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Gpu")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Os")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("RAM")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("PhoneId");

                            b1.ToTable("Phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId");
                        });

                    b.Navigation("BatteryDetails")
                        .IsRequired();

                    b.Navigation("BodyDimensions")
                        .IsRequired();

                    b.Navigation("CameraDetails")
                        .IsRequired();

                    b.Navigation("DisplayDetails")
                        .IsRequired();

                    b.Navigation("PlatformDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
