// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiCompare.Data;

#nullable disable

namespace OptiCompare.Migrations
{
    [DbContext(typeof(OptiCompareDbContext))]
    [Migration("20240331175346_Pagination_PropsMaxLengthTweak")]
    partial class Pagination_PropsMaxLengthTweak
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OptiCompare.Models.Phone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("hasNetwork5GBands")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("image")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("modelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("price")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("storage")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("phones");
                });

            modelBuilder.Entity("OptiCompare.Models.Phone", b =>
                {
                    b.OwnsOne("OptiCompare.Models.BatteryDetails", "batteryDetails", b1 =>
                        {
                            b1.Property<int>("Phoneid")
                                .HasColumnType("int");

                            b1.Property<string>("batteryCapacity")
                                .HasColumnType("longtext");

                            b1.Property<string>("batteryLifeTest")
                                .HasColumnType("longtext");

                            b1.Property<string>("chargingSpeed")
                                .HasColumnType("longtext");

                            b1.HasKey("Phoneid");

                            b1.ToTable("phones");

                            b1.WithOwner()
                                .HasForeignKey("Phoneid");
                        });

                    b.OwnsOne("OptiCompare.PhoneSpecs.BodyDimensions", "bodyDimensions", b1 =>
                        {
                            b1.Property<int>("Phoneid")
                                .HasColumnType("int");

                            b1.Property<string>("bodyHeight")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("bodyThickness")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("bodyWeight")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("bodyWidth")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.HasKey("Phoneid");

                            b1.ToTable("phones");

                            b1.WithOwner()
                                .HasForeignKey("Phoneid");
                        });

                    b.OwnsOne("OptiCompare.PhoneSpecs.CameraDetails", "cameraDetails", b1 =>
                        {
                            b1.Property<int>("Phoneid")
                                .HasColumnType("int");

                            b1.Property<string>("frontCameraDetails")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("mainCameraDetails")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.HasKey("Phoneid");

                            b1.ToTable("phones");

                            b1.WithOwner()
                                .HasForeignKey("Phoneid");
                        });

                    b.OwnsOne("OptiCompare.PhoneSpecs.DisplayDetails", "displayDetails", b1 =>
                        {
                            b1.Property<int>("Phoneid")
                                .HasColumnType("int");

                            b1.Property<string>("displayProtection")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("displayResolution")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("displaySize")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("displayType")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.HasKey("Phoneid");

                            b1.ToTable("phones");

                            b1.WithOwner()
                                .HasForeignKey("Phoneid");
                        });

                    b.OwnsOne("OptiCompare.PhoneSpecs.PlatformDetails", "platformDetails", b1 =>
                        {
                            b1.Property<int>("Phoneid")
                                .HasColumnType("int");

                            b1.Property<string>("cpu")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("gpu")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("os")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("ram")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.HasKey("Phoneid");

                            b1.ToTable("phones");

                            b1.WithOwner()
                                .HasForeignKey("Phoneid");
                        });

                    b.Navigation("batteryDetails")
                        .IsRequired();

                    b.Navigation("bodyDimensions")
                        .IsRequired();

                    b.Navigation("cameraDetails")
                        .IsRequired();

                    b.Navigation("displayDetails")
                        .IsRequired();

                    b.Navigation("platformDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
