// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiCompare.Data;

#nullable disable

namespace OptiCompare.Migrations
{
    [DbContext(typeof(OptiCompareDbContext))]
    [Migration("20240408094533_AddBatteryDetails")]
    partial class AddBatteryDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OptiCompare.Models.BatteryDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<string>("batteryCapacity")
                        .HasColumnType("longtext");

                    b.Property<string>("batteryLifeTest")
                        .HasColumnType("longtext");

                    b.Property<string>("chargingSpeed")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.ToTable("BatteryDetails");
                });

            modelBuilder.Entity("OptiCompare.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("hasNetwork5GBands")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("image")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("modelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("price")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("storage")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("phones");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.BodyDimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<string>("bodyHeight")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("bodyThickness")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("bodyWeight")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("bodyWidth")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.ToTable("BodyDimensions");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.CameraDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<string>("frontCameraDetails")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("mainCameraDetails")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.ToTable("CameraDetails");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.DisplayDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<string>("displayProtection")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("displayResolution")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("displaySize")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("displayType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.ToTable("DisplayDetails");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.PlatformDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<string>("cpu")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("gpu")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("os")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ram")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.ToTable("PlatformDetails");
                });

            modelBuilder.Entity("OptiCompare.Models.BatteryDetails", b =>
                {
                    b.HasOne("OptiCompare.Models.Phone", "Phone")
                        .WithOne("batteryDetails")
                        .HasForeignKey("OptiCompare.Models.BatteryDetails", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.BodyDimensions", b =>
                {
                    b.HasOne("OptiCompare.Models.Phone", "Phone")
                        .WithOne("bodyDimensions")
                        .HasForeignKey("OptiCompare.PhoneSpecs.BodyDimensions", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.CameraDetails", b =>
                {
                    b.HasOne("OptiCompare.Models.Phone", "Phone")
                        .WithOne("cameraDetails")
                        .HasForeignKey("OptiCompare.PhoneSpecs.CameraDetails", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.DisplayDetails", b =>
                {
                    b.HasOne("OptiCompare.Models.Phone", "Phone")
                        .WithOne("displayDetails")
                        .HasForeignKey("OptiCompare.PhoneSpecs.DisplayDetails", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("OptiCompare.PhoneSpecs.PlatformDetails", b =>
                {
                    b.HasOne("OptiCompare.Models.Phone", "Phone")
                        .WithOne("platformDetails")
                        .HasForeignKey("OptiCompare.PhoneSpecs.PlatformDetails", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("OptiCompare.Models.Phone", b =>
                {
                    b.Navigation("batteryDetails")
                        .IsRequired();

                    b.Navigation("bodyDimensions")
                        .IsRequired();

                    b.Navigation("cameraDetails")
                        .IsRequired();

                    b.Navigation("displayDetails")
                        .IsRequired();

                    b.Navigation("platformDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
